<h1> Tensorflow Basic Operations </h1> 

Importing tensorflow module

In [23]:
import tensorflow as tf
import numpy as np

In [24]:
a = tf.constant(2)
b = tf.constant(4)
m = tf.multiply(a, b)
with tf.Session() as sess:
    print("{}".format(sess.run(m)))

8


In [25]:
add = tf.add(a, b)
with tf.Session() as sess:
    print("{}".format(sess.run(add, feed_dict={a: 6, b: 9})))

15


In [37]:
mat1 = tf.constant(np.random.rand(3, 3))
mat2 = tf.constant(np.random.rand(3, 3))
prod = tf.matmul(mat1, mat2)

with tf.Session() as sess:
    print("mat1:\n{}".format(sess.run(mat1)))
    print("mat2:\n{}".format(sess.run(mat2)))
    print("mat1xmat2:\n{}".format(sess.run(prod)))

mat1:
[[ 0.09305602  0.68706512  0.8807492 ]
 [ 0.82866915  0.29357049  0.83552585]
 [ 0.14724203  0.35498805  0.88306873]]
mat2:
[[ 0.65701136  0.43957443  0.68610842]
 [ 0.71543003  0.25626376  0.53418071]
 [ 0.68010274  0.55484042  0.23549671]]
mat1xmat2:
[[ 1.15168583  0.7056502   0.63827699]
 [ 1.32271761  0.90307677  0.92214016]
 [ 0.95128626  0.64565663  0.49861154]]
